<?php

namespace App\Http\Controllers;

use App\Models\Plugin;
use App\Models\Category;
use App\Http\Requests\StorePluginRequest;
use App\Http\Requests\UpdatePluginRequest;
use App\Services\FileUploadService;
use App\Services\CacheService;
use Inertia\Inertia;
use Illuminate\Support\Facades\Log;
use Illuminate\Database\QueryException;

class PluginController extends Controller
{
    protected FileUploadService $fileUploadService;
    protected CacheService $cacheService;

    public function __construct(FileUploadService $fileUploadService, CacheService $cacheService)
    {
        $this->middleware(['auth', 'verified']);
        $this->fileUploadService = $fileUploadService;
        $this->cacheService = $cacheService;
    }

    public function index()
    {
        try {
            $plugins = auth()->user()->plugins()
                ->with('category')
                ->latest()
                ->paginate(10);

            return Inertia::render('Plugins/Index', [
                'plugins' => $plugins,
            ]);
        } catch (QueryException $e) {
            Log::error('Database error loading user plugins', [
                'user_id' => auth()->id(),
                'error' => $e->getMessage(),
                'request_path' => request()->path(),
                'ip_address' => request()->ip(),
            ]);
            
            return Inertia::render('Plugins/Index', [
                'plugins' => [],
                'error' => 'Unable to load plugins. Please try again later.',
            ]);
        } catch (\Exception $e) {
            Log::error('Error loading user plugins', [
                'user_id' => auth()->id(),
                'error' => $e->getMessage(),
                'request_path' => request()->path(),
                'ip_address' => request()->ip(),
                'trace' => $e->getTraceAsString(),
            ]);
            
            return Inertia::render('Plugins/Index', [
                'plugins' => [],
                'error' => 'An unexpected error occurred. Please try again later.',
            ]);
        }
    }

    public function create()
    {
        $categories = Category::all();

        return Inertia::render('Plugins/Create', [
            'categories' => $categories,
        ]);
    }

    public function store(StorePluginRequest $request)
    {
        try {
            $data = $request->validated();
            
            // Sanitize description to prevent XSS
            $data['description'] = strip_tags($data['description'], '<p><br><strong><em><ul><ol><li><a>');
            
            // Set user and status (slug is auto-generated by model)
            $data['user_id'] = auth()->id();
            $data['status'] = 'pending'; // Requires admin approval
            
            // Handle logo upload
            if ($request->hasFile('logo')) {
                $data['logo_path'] = $this->fileUploadService->uploadPluginLogo($request->file('logo'));
            }
            
            $plugin = Plugin::create($data);
            
            return redirect()->route('plugins.index')
                ->with('success', 'Plugin submitted successfully and is pending approval.');
        } catch (QueryException $e) {
            Log::error('Database error creating plugin', [
                'user_id' => auth()->id(),
                'error' => $e->getMessage(),
                'request_path' => request()->path(),
                'ip_address' => request()->ip(),
            ]);
            
            return back()->withInput()
                ->with('error', 'Unable to create plugin. Please try again.');
        } catch (\Exception $e) {
            Log::error('Error creating plugin', [
                'user_id' => auth()->id(),
                'error' => $e->getMessage(),
                'request_path' => request()->path(),
                'ip_address' => request()->ip(),
                'trace' => $e->getTraceAsString(),
            ]);
            
            return back()->withInput()
                ->with('error', 'An unexpected error occurred. Please try again.');
        }
    }

    public function edit(Plugin $plugin)
    {
        // Ensure user owns the plugin
        if (!$plugin->isOwnedBy(auth()->user())) {
            abort(403);
        }

        $categories = Category::all();

        return Inertia::render('Plugins/Edit', [
            'plugin' => $plugin,
            'categories' => $categories,
        ]);
    }

    public function update(UpdatePluginRequest $request, Plugin $plugin)
    {
        try {
            $data = $request->validated();
            
            // Sanitize description to prevent XSS
            $data['description'] = strip_tags($data['description'], '<p><br><strong><em><ul><ol><li><a>');
            
            // Slug is auto-updated by model if name changes
            
            // Handle logo upload
            if ($request->hasFile('logo')) {
                $data['logo_path'] = $this->fileUploadService->uploadPluginLogo(
                    $request->file('logo'),
                    $plugin->logo_path
                );
            }
            
            // Reset to pending if active plugin is updated
            if ($plugin->status === 'active') {
                $data['status'] = 'pending';
            }
            
            $plugin->update($data);
            
            // Invalidate plugin cache
            $this->cacheService->invalidatePlugin($plugin->id);
            
            return redirect()->route('plugins.index')
                ->with('success', 'Plugin updated successfully.');
        } catch (QueryException $e) {
            Log::error('Database error updating plugin', [
                'plugin_id' => $plugin->id,
                'user_id' => auth()->id(),
                'error' => $e->getMessage(),
                'request_path' => request()->path(),
                'ip_address' => request()->ip(),
            ]);
            
            return back()->withInput()
                ->with('error', 'Unable to update plugin. Please try again.');
        } catch (\Exception $e) {
            Log::error('Error updating plugin', [
                'plugin_id' => $plugin->id,
                'user_id' => auth()->id(),
                'error' => $e->getMessage(),
                'request_path' => request()->path(),
                'ip_address' => request()->ip(),
                'trace' => $e->getTraceAsString(),
            ]);
            
            return back()->withInput()
                ->with('error', 'An unexpected error occurred. Please try again.');
        }
    }

    public function destroy(Plugin $plugin)
    {
        try {
            // Ensure user owns the plugin
            if (!$plugin->isOwnedBy(auth()->user())) {
                abort(403);
            }

            $pluginId = $plugin->id;
            $plugin->delete();
            
            // Invalidate plugin cache
            $this->cacheService->invalidatePlugin($pluginId);
            
            return redirect()->route('plugins.index')
                ->with('success', 'Plugin deleted successfully.');
        } catch (QueryException $e) {
            Log::error('Database error deleting plugin', [
                'plugin_id' => $plugin->id,
                'user_id' => auth()->id(),
                'error' => $e->getMessage(),
                'request_path' => request()->path(),
                'ip_address' => request()->ip(),
            ]);
            
            return back()->with('error', 'Unable to delete plugin. Please try again.');
        } catch (\Exception $e) {
            Log::error('Error deleting plugin', [
                'plugin_id' => $plugin->id,
                'user_id' => auth()->id(),
                'error' => $e->getMessage(),
                'request_path' => request()->path(),
                'ip_address' => request()->ip(),
                'trace' => $e->getTraceAsString(),
            ]);
            
            return back()->with('error', 'An unexpected error occurred. Please try again.');
        }
    }
}
